services:
  # SAB Lanyard MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: sablanyard_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: minipreorder
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - sablanyard_network

  # SAB Lanyard Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - PORT=5000
        - BASE_URL=http://localhost:5000
        - MONGODB_URI=mongodb://admin:password123@mongodb:27017/minipreorder?authSource=admin
        - JWT_SECRET=your-super-secret-jwt-key-here
        - ADMIN_EMAIL=sab@fit.hcmus.edu.vn
        - ADMIN_USERNAME=admin
        - ADMIN_PASSWORD=admin123
    pull_policy: always
    container_name: sablanyard_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - sablanyard_network

  # SAB Lanyard Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - REACT_APP_API_URL=http://localhost:5000/api
        - REACT_APP_BANK_NAME_ID=your-bank-name-id-here
        - REACT_APP_ACCOUNT_NO=ACCOUNT_NUMBER
    pull_policy: always
    container_name: sablanyard_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - sablanyard_network

volumes:
  mongodb_data:

networks:
  sablanyard_network:
    driver: bridge
