services:
  # SAB Lanyard MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: sablanyard_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: sablanyard
    expose:
      - 27017
    volumes:
      - mongodb_data:/data/db
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - sablanyard_network

  # SAB Lanyard Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    pull_policy: always
    container_name: sablanyard_backend
    restart: unless-stopped
    expose:
      - 5000

    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - sablanyard_network    
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/minipreorder?authSource: admin
      JWT_SECRET: your-super-secret-jwt-key-here
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USER: your-email@gmail.com
      EMAIL_PASS: your-app-password
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin123

  # SAB Lanyard Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sablanyard_frontend
    restart: unless-stopped
    expose:
      - 3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - sablanyard_network
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
      REACT_APP_BANK_ID: BANK_NAME
      REACT_APP_ACCOUNT_NO: ACCOUNT_NUMBER

volumes:
  mongodb_data:

networks:
  sablanyard_network:
    external: true
    name: multi-domain
